# Generated by Django 3.1.4 on 2020-12-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedicated_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, null=True, upload_to='post_files'),
        ),
    ]
