# Generated by Django 3.1.4 on 2020-12-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedicated_page', '0002_post_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_file',
        ),
        migrations.AddField(
            model_name='post',
            name='uploaded_file_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
