# Generated by Django 3.1.4 on 2020-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedicated_page', '0003_auto_20201213_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_file_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
