# Generated by Django 3.1.2 on 2020-12-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedicated_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='uploaded_file_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='uploaded_file_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
